### ISSUE TITLE
Enable --version switch

### ISSUE THREAD

**Issue by chrberndt** [inofix/maestro#29]
-V is working, --version not, e.g.

`berndt@x220:~$ maestro.sh -V`
`Version: v1.3-14`
`berndt@x220:~$ maestro.sh --version`
`usage: /home/berndt/bin/maestro.sh [options] action`

**Comment by zwischenloesung** [comment]
Thanks. Issue is fixed in Version: v1.3-19-g209ec10.

**Comment by chrberndt** [comment]
cool, works
